import unittest
from utils.missing import find_missing

# do not edit this file
class TestUtils(unittest.TestCase):
  def test_1(self):
    manifest = [
        '6ff30d23-27dc-4d5b-8d83-6412a872fc49',
        'f3f359f7-e429-4080-9b28-b96365d581e1',
        'ce53036f-8c9e-4dd9-a9e2-9a9469b1313e',
        '9af1d4b6-b194-4548-86c3-2febf995fb54',
        'a856c7aa-4215-4d1b-8e9b-d8ed8e166e12',
        'a6232ec4-0ace-4380-ab3b-a4bebad86f9f',
        'c404603b-8f10-4110-bfe3-608fa1c3d54a',
        'b56a155d-5e86-4a11-bc6c-34abf5cf345d',
    ]
    sack = [
        '6ff30d23-27dc-4d5b-8d83-6412a872fc49',
        'ce53036f-8c9e-4dd9-a9e2-9a9469b1313e',
        '9af1d4b6-b194-4548-86c3-2febf995fb54',
        'a856c7aa-4215-4d1b-8e9b-d8ed8e166e12',
        'c404603b-8f10-4110-bfe3-608fa1c3d54a',
        'b56a155d-5e86-4a11-bc6c-34abf5cf345d',
    ]
    items = find_missing(manifest, sack)
    self.assertEqual(len(items), 2)
    self.assertTrue('Peace on Earth' in [x['name'] for x in items])
    self.assertTrue('PlayStation 5' in [x['name'] for x in items])
  def test_2(self):
    manifest = [
        '6ff30d23-27dc-4d5b-8d83-6412a872fc49',
        'f3f359f7-e429-4080-9b28-b96365d581e1',
        'ce53036f-8c9e-4dd9-a9e2-9a9469b1313e',
        '9af1d4b6-b194-4548-86c3-2febf995fb54',
        'a856c7aa-4215-4d1b-8e9b-d8ed8e166e12',
        'c404603b-8f10-4110-bfe3-608fa1c3d54a',
        'b56a155d-5e86-4a11-bc6c-34abf5cf345d',
    ]
    sack = [
        'a856c7aa-4215-4d1b-8e9b-d8ed8e166e12',
        'c404603b-8f10-4110-bfe3-608fa1c3d54a',
        'b56a155d-5e86-4a11-bc6c-34abf5cf345d',
    ]
    items = find_missing(manifest, sack)
    self.assertEqual(len(items), 4)
    self.assertTrue('Doll' in [x['name'] for x in items])
    self.assertTrue('PlayStation 5' in [x['name'] for x in items])
    self.assertTrue('Bike' in [x['name'] for x in items])

if __name__ == '__main__':
    unittest.main()